### PR TITLE
Added support for OLD3DS SPIDER v7168 KOR (v10.2..v10.5)

### PR DESCRIPTION
**Pull request by d3m3vilurr**
Work tested on the 10.3K

### CODE REVIEW

**Comment by d3m3vilurr** [comment]
I cannot dump heap memory area using NTR with emunand (ntr mode unloaded at enter browser unlike new 3ds)
So can't port other versions.

**Comment by d3m3vilurr** [comment]
@yellows8 can you share your heap dump method?

**Comment by yellows8** [comment]
That's a codebase which is currently private.

**Comment by d3m3vilurr** [comment]
yea... I know.. :(
I hope to be opensource that :)

**Pull request merged**
